tree_name: "simOmtfPhase2Digis/OMTFHitsTree"
muon_vars:
  - "muonEta"
  - "muonPhi"
  - "muonQOverPt"
  - "muonQPt"
omtf_vars:
  - "omtfEta"
  - "omtfPhi"
  - "omtfPt"
  - "omtfUPt"
stub_vars:
  - "inputStubEtaG"
  - "inputStubCosPhi"
  - "inputStubSinPhi"
  - "inputStubR"
  - "inputStubLayer"
  - "inputStubPhiG"
  #- "inputStubLayOrder"
  - "inputStubType"
  - "inputStubIsMatched"
target_vars:
  - "muonQOverPt"