tree_name: "simOmtfPhase2Digis/OMTFHitsTree"
muon_vars:
  - "muonEta"
  - "muonPhi"
  - "muonQOverPt"
  - "muonQPt"
omtf_vars:
  - "omtfEta"
  - "omtfPhi"
  - "omtfPt"
  - "omtfUPt"
stub_vars:
  - "stubEtaG"
  - "stubPhiG"
  - "stubR"
  - "stubLayer"
  - "stubType"
target_vars:
  - "muonQOverPt"