tree_vars = [
    'eventNum', 'muonEvent', 'muonPt', 'muonEta', 'muonPhi', 'muonPropEta',
    'muonPropPhi', 'muonCharge', 'muonDxy', 'muonRho', 'omtfPt', 'omtfUPt',
    'omtfEta', 'omtfPhi', 'omtfCharge', 'omtfHwEta', 'omtfProcessor',
    'omtfScore', 'omtfQuality', 'omtfRefLayer', 'omtfRefHitNum',
    'omtfFiredLayers', 'stubNo', 'stubLayer', 'stubQuality',
    'stubZ', 'stubValid', 'stubEta', 'stubPhiDist', 'stubPhi',
    'stubIsRefLayer', 'stubTiming', 'stubDetId', 'stubBx', 'stubPhiB',
    'stubR', 'stubDeltaR', 'stubType', 'inputStubNo', 'inputStubLayer',
    'inputStubQuality', 'inputStubZ', 'inputStubProc', 'inputStubEta',
    'inputStubPhi', 'inputStubTiming',
    'inputStubDetId', 'inputStubBx', 'inputStubPhiB', 'inputStubR',
    'inputStubType', 'inputStubIsMatched', 'deltaEta', 'deltaPhi'
]

# Crear configuración de plots para cada variable con configuraciones básicas
plots = {}
for var in tree_vars:
    plots[var] = {
        'variable'   : var,
        'bins'       : 100,                   # Puedes ajustar o implementar lógica para diferentes binning
        'extra cuts' : 'True',                # O personalizar según la variable
        'xlabel'     : var,
        'ylabel'     : 'Yields',
        'xrange'     : None,                  # Puedes definir rangos por defecto o dejar None
        'ExtraSpam'  : "",
        'logY'       : False,
        'logX'       : False,
        'grid'       : True,
        'savename'   : f'[PDIR]/[DATASET]/{var}',
        'executer'   : 'plotter',
        'type'       : '1D'
    }

'''
plots = {
    #---------------------------#####################---------------------------#
    ############################---------------------############################
    ############################         PLOT        ############################
    ############################        YIELDS       ############################
    #---------------------------#####################---------------------------#
    'muonPt' : {'variable'   : 'muonPt',
                'bins'       : 100,  # can be a number or a list of bin edges
                'extra cuts' : 'True', # Applied at per object level only in this plot
                #Plotting thingies
                'xlabel'     : 'Gen $p_T$ (GeV)',
                'ylabel'     : 'Yields',
                'xrange'     : [0,400],
                'ExtraSpam'  :  "",
                'logY'       : False,
                'logX'       : False,
                'grid'       : True,
                'savename'   : '[PDIR]/[DATASET]/Observables/muonPt',
                'executer'   : 'plotter', # Safeguard to not run the plot outside of what was designed for it
                'type'       : '1D',
   },
   'muonEta' : {'variable'   : 'muonEta',
                'bins'       : 100,  # can be a number or a list of bin edges
                'extra cuts' : 'True', # Applied at per object level only in this plot
                #Plotting thingies
                'xlabel'     : 'Gen $\eta$',
                'ylabel'     : 'Yields',
                'xrange'     : [-2.4,2.4],
                'ExtraSpam'  :  "",
                'logY'       : False,
                'logX'       : False,
                'grid'       : True,
                'savename'   : '[PDIR]/[DATASET]/Observables/muonEta',
                'executer'   : 'plotter', # Safeguard to not run the plot outside of what was designed for it
                'type'       : '1D',
   },
   'muonPhi' : {'variable'   : 'muonPhi',
                'bins'       : 100,  # can be a number or a list of bin edges
                'extra cuts' : 'True', # Applied at per object level only in this plot
                #Plotting thingies
                'xlabel'     : 'Gen $\phi$',
                'ylabel'     : 'Yields',
                'xrange'     : [-3.14,3.14],
                'ExtraSpam'  :  "",
                'logY'       : False,
                'logX'       : False,
                'grid'       : True,
                'savename'   : '[PDIR]/[DATASET]/Observables/muonPhi',
                'executer'   : 'plotter', # Safeguard to not run the plot outside of what was designed for it
                'type'       : '1D',
   },
   'muonPropEta' : {'variable'   : 'muonPropEta',
                'bins'       : 100,  # can be a number or a list of bin edges
                'extra cuts' : 'True', # Applied at per object level only in this plot
                #Plotting thingies
                'xlabel'     : 'Prop $\eta$',
                'ylabel'     : 'Yields',
                'xrange'     : [-2.4,2.4],
                'ExtraSpam'  :  "",
                'logY'       : False,
                'logX'       : False,
                'grid'       : True,
                'savename'   : '[PDIR]/[DATASET]/Observables/muonPropEta',
                'executer'   : 'plotter', # Safeguard to not run the plot outside of what was designed for it
                'type'       : '1D',
   },
    'muonPropPhi' : {'variable'   : 'muonPropPhi',
                 'bins'       : 100,  # can be a number or a list of bin edges
                 'extra cuts' : 'True', # Applied at per object level only in this plot
                 #Plotting thingies
                 'xlabel'     : 'Prop $\phi$',
                 'ylabel'     : 'Yields',
                 'xrange'     : [-3.14,3.14],
                 'ExtraSpam'  :  "",
                 'logY'       : False,
                 'logX'       : False,
                 'grid'       : True,
                 'savename'   : '[PDIR]/[DATASET]/Observables/muonPropPhi',
                 'executer'   : 'plotter', # Safeguard to not run the plot outside of what was designed for it
                 'type'       : '1D',
    },
    'muonCharge' : {'variable'   : 'muonCharge',
                    'bins'       : 100,  # can be a number or a list of bin edges
                    'extra cuts' : 'True', # Applied at per object level only in this plot
                    #Plotting thingies
                    'xlabel'     : 'Charge',
                    'ylabel'     : 'Yields',
                    'xrange'     : [-2,2],
                    'ExtraSpam'  :  "",
                    'logY'       : False,
                    'logX'       : False,
                    'grid'       : True,
                    'savename'   : '[PDIR]/[DATASET]/Observables/muonCharge',
                    'executer'   : 'plotter', # Safeguard to not run the plot outside of what was designed for it
                    'type'       : '1D',
        },
    'muonDxy' : {'variable'   : 'muonDxy',
                    'bins'       : 100,  # can be a number or a list of bin edges
                    'extra cuts' : 'True', # Applied at per object level only in this plot
                    #Plotting thingies
                    'xlabel'     : 'dxy',
                    'ylabel'     : 'Yields',
                    'xrange'     : [-100,100],
                    'ExtraSpam'  :  "",
                    'logY'       : False,
                    'logX'       : False,
                    'grid'       : True,
                    'savename'   : '[PDIR]/[DATASET]/Observables/muonDxy',
                    'executer'   : 'plotter', # Safeguard to not run the plot outside of what was designed for it
                    'type'       : '1D',
        },
    'muonRho' : {'variable'   : 'muonRho',
                    'bins'       : 100,  # can be a number or a list of bin edges
                    'extra cuts' : 'True', # Applied at per object level only in this plot
                    #Plotting thingies
                    'xlabel'     : 'rho',
                    'ylabel'     : 'Yields',
                    'xrange'     : [-100,100],
                    'ExtraSpam'  :  "",
                    'logY'       : False,
                    'logX'       : False,
                    'grid'       : True,
                    'savename'   : '[PDIR]/[DATASET]/Observables/muonRho',
                    'executer'   : 'plotter', # Safeguard to not run the plot outside of what was designed for it
                    'type'       : '1D',
        },
    'omtfPt' : {'variable'   : 'omtfPt',
                    'bins'       : 100,  # can be a number or a list of bin edges
                    'extra cuts' : 'True', # Applied at per object level only in this plot
                    #Plotting thingies
                    'xlabel'     : 'OMTF $p_T$ (GeV)',
                    'ylabel'     : 'Yields',
                    'xrange'     : [0,400],
                    'ExtraSpam'  :  "",
                    'logY'       : False,
                    'logX'       : False,
                    'grid'       : True,
                    'savename'   : '[PDIR]/[DATASET]/Observables/omtfPt',
                    'executer'   : 'plotter', # Safeguard to not run the plot outside of what was designed for it
                    'type'       : '1D',
        },
        'omtfUPt' : {'variable'   : 'omtfUPt',
                    'bins'       : 100,  # can be a number or a list of bin edges
                    'extra cuts' : 'True', # Applied at per object level only in this plot
                    #Plotting thingies
                    'xlabel'     : 'OMTF unconstrained $p_T$ (GeV)',
                    'ylabel'     : 'Yields',
                    'xrange'     : [0,400],
                    'ExtraSpam'  :  "",
                    'logY'       : False,
                    'logX'       : False,
                    'grid'       : True,
                    'savename'   : '[PDIR]/[DATASET]/Observables/omtfUPt',
                    'executer'   : 'plotter', # Safeguard to not run the plot outside of what was designed for it
                    'type'       : '1D',
        },

    'omtfEta' : {'variable'   : 'omtfEta',
                    'bins'       : 100,  # can be a number or a list of bin edges
                    'extra cuts' : 'True', # Applied at per object level only in this plot
                    #Plotting thingies
                    'xlabel'     : 'OMTF $\eta$',
                    'ylabel'     : 'Yields',
                    'xrange'     : [-2.4,2.4],
                    'ExtraSpam'  :  "",
                    'logY'       : False,
                    'logX'       : False,
                    'grid'       : True,
                    'savename'   : '[PDIR]/[DATASET]/Observables/omtfEta',
                    'executer'   : 'plotter', # Safeguard to not run the plot outside of what was designed for it
                    'type'       : '1D',
        },
    'omtfPhi' : {'variable'   : 'omtfPhi',
                    'bins'       : 100,  # can be a number or a list of bin edges
                    'extra cuts' : 'True', # Applied at per object level only in this plot
                    #Plotting thingies
                    'xlabel'     : 'OMTF $\phi$',
                    'ylabel'     : 'Yields',
                    'xrange'     : [-1000,1000],
                    'ExtraSpam'  :  "",
                    'logY'       : False,
                    'logX'       : False,
                    'grid'       : True,
                    'savename'   : '[PDIR]/[DATASET]/Observables/omtfPhi',
                    'executer'   : 'plotter', # Safeguard to not run the plot outside of what was designed for it
                    'type'       : '1D',
        },
    'omtfCharge' : {'variable'   : 'omtfCharge',
                    'bins'       : 100,  # can be a number or a list of bin edges
                    'extra cuts' : 'True', # Applied at per object level only in this plot
                    #Plotting thingies
                    'xlabel'     : 'OMTF Charge',
                    'ylabel'     : 'Yields',
                    'xrange'     : [-2,2],
                    'ExtraSpam'  :  "",
                    'logY'       : False,
                    'logX'       : False,
                    'grid'       : True,
                    'savename'   : '[PDIR]/[DATASET]/Observables/omtfCharge',
                    'executer'   : 'plotter', # Safeguard to not run the plot outside of what was designed for it
                    'type'       : '1D',
    },
    'omtfScore' : {'variable'   : 'omtfScore',
                    'bins'       : 100,  # can be a number or a list of bin edges
                    'extra cuts' : 'True', # Applied at per object level only in this plot
                    #Plotting thingies
                    'xlabel'     : 'OMTF Score',
                    'ylabel'     : 'Yields',
                    'xrange'     : [0,1000],
                    'ExtraSpam'  :  "",
                    'logY'       : False,
                    'logX'       : False,
                    'grid'       : True,
                    'savename'   : '[PDIR]/[DATASET]/Observables/omtfScore',
                    'executer'   : 'plotter', # Safeguard to not run the plot outside of what was designed for it
                    'type'       : '1D',
    },
    'omtfRefHitNum' : {'variable'   : 'omtfRefHitNum',
                    'bins'       : 20,  # can be a number or a list of bin edges
                    'extra cuts' : 'True', # Applied at per object level only in this plot
                    #Plotting thingies
                    'xlabel'     : 'OMTF RefHitNum',
                    'ylabel'     : 'Yields',
                    'xrange'     : [-0.5,19.5],
                    'ExtraSpam'  :  "",
                    'logY'       : False,
                    'logX'       : False,
                    'grid'       : True,
                    'savename'   : '[PDIR]/[DATASET]/Observables/omtfRefHitNum',
                    'executer'   : 'plotter', # Safeguard to not run the plot outside of what was designed for it
                    'type'       : '1D',
    },
    'omtfFiredLayers'   : {'variable'   : 'omtfFiredLayers',
                    'bins'       : 100,  # can be a number or a list of bin edges
                    'extra cuts' : 'True', # Applied at per object level only in this plot
                    #Plotting thingies
                    'xlabel'     : 'OMTF FiredLayers',
                    'ylabel'     : 'Yields',
                    'xrange'     : [0,20],
                    'ExtraSpam'  :  "",
                    'logY'       : False,
                    'logX'       : False,
                    'grid'       : True,
                    'savename'   : '[PDIR]/[DATASET]/Observables/omtfFiredLayers',
                    'executer'   : 'plotter', # Safeguard to not run the plot outside of what was designed for it
                    'type'       : '1D',
    },
    'omtfQuality' : {'variable'   : 'omtfQuality',
                    'bins'       : 20,  # can be a number or a list of bin edges
                    'extra cuts' : 'True', # Applied at per object level only in this plot
                    #Plotting thingies
                    'xlabel'     : 'OMTF Quality',
                    'ylabel'     : 'Yields',
                    'xrange'     : [0,20],
                    'ExtraSpam'  :  "",
                    'logY'       : False,
                    'logX'       : False,
                    'grid'       : True,
                    'savename'   : '[PDIR]/[DATASET]/Observables/omtfQuality',
                    'executer'   : 'plotter', # Safeguard to not run the plot outside of what was designed for it
                    'type'       : '1D',
    },
    'stubsN' : {'variable'   : 'stubNo',
                    'bins'       : 10,  # can be a number or a list of bin edges
                    'extra cuts' : 'True', # Applied at per object level only in this plot
                    #Plotting thingies
                    'xlabel'     : '# stubs',
                    'ylabel'     : 'Yields',
                    'xrange'     : [0.5,10.5],
                    'ExtraSpam'  :  "",
                    'logY'       : False,
                    'logX'       : False,
                    'grid'       : True,
                    'savename'   : '[PDIR]/[DATASET]/Observables/stubNo',
                    'executer'   : 'plotter', # Safeguard to not run the plot outside of what was designed for it
                    'type'       : '1D',
    },
    'stubPhi' : {'variable'   : 'stubPhi',
                    'bins'       : 1000,  # can be a number or a list of bin edges
                    'extra cuts' : 'True', # Applied at per object level only in this plot
                    #Plotting thingies
                    'xlabel'     : '$\phi$ (stubs)',
                    'ylabel'     : 'Yields',
                    'xrange'     : [-1000,1000],
                    'ExtraSpam'  :  "",
                    'logY'       : False,
                    'logX'       : False,
                    'grid'       : True,
                    'savename'   : '[PDIR]/[DATASET]/Observables/stubPhi',
                    'executer'   : 'plotter', # Safeguard to not run the plot outside of what was designed for it
                    'type'       : '1D',
    },
    'stubPhiB' : {'variable'   : 'stubPhiB',
                    'bins'       : 100,  # can be a number or a list of bin edges
                    'extra cuts' : 'True', # Applied at per object level only in this plot
                    #Plotting thingies
                    'xlabel'     : '$\phi_B$ stubs',
                    'ylabel'     : 'Yields',
                    'xrange'     : [-500,500],
                    'ExtraSpam'  :  "",
                    'logY'       : False,
                    'logX'       : False,
                    'grid'       : True,
                    'savename'   : '[PDIR]/[DATASET]/Observables/stubPhiB',
                    'executer'   : 'plotter', # Safeguard to not run the plot outside of what was designed for it
                    'type'       : '1D',
    },
    'stubEta' : {'variable'   : 'stubEta',
                    'bins'       : 70,  # can be a number or a list of bin edges
                    'extra cuts' : 'True', # Applied at per object level only in this plot
                    #Plotting thingies
                    'xlabel'     : '$\eta$ (stubs)',
                    'ylabel'     : 'Yields',
                    'xrange'     : [70,140],
                    'ExtraSpam'  :  "",
                    'logY'       : False,
                    'logX'       : False,
                    'grid'       : True,
                    'savename'   : '[PDIR]/[DATASET]/Observables/stubEta',
                    'executer'   : 'plotter', # Safeguard to not run the plot outside of what was designed for it
                    'type'       : '1D',
    },
    'stubPhiDist' : {'variable'   : 'stubPhiDist',
                      'bins'       : 100,
                      'extra cuts' : 'True',
                      'xlabel'     : 'stubEtaDist',
                      'ylabel'     : 'Yields',
                      'xrange'     : [-100,100],
                      'ExtraSpam'  :  "",
                      'logY'       : False,
                      'logX'       : False,
                      'grid'       : True,
                      'savename'   : '[PDIR]/[DATASET]/Observables/stubPhiDist',
                      'executer'   : 'plotter',
                      'type'       : '1D',
    },

    'stubEtaDist' : {'variable'   : 'stubEtaDist',
                      'bins'       : 100,
                      'extra cuts' : 'True',
                      'xlabel'     : 'stubEtaDist',
                      'ylabel'     : 'Yields',
                      'xrange'     : [0,50],
                      'ExtraSpam'  :  "",
                      'logY'       : False,
                      'logX'       : False,
                      'grid'       : True,
                      'savename'   : '[PDIR]/[DATASET]/Observables/stubEtaDist',
                      'executer'   : 'plotter',
                      'type'       : '1D',
    },
    'stubQuality' : {'variable'   : 'stubQuality',
                      'bins'       : 12,
                      'extra cuts' : 'True',
                      'xlabel'     : 'stubQuality',
                      'ylabel'     : 'Yields',
                      'xrange'     : [0.5,12.5],
                      'ExtraSpam'  :  "",
                      'logY'       : False,
                      'logX'       : False,
                      'grid'       : True,
                      'savename'   : '[PDIR]/[DATASET]/Observables/stubQuality',
                      'executer'   : 'plotter',
                      'type'       : '1D',
    },
   'stubBx' : {'variable'   : 'stubBx',
                        'bins'       : 5,
                        'extra cuts' : 'True',
                        'xlabel'     : 'stubBx',
                        'ylabel'     : 'Yields',
                        'xrange'     : [-2,2],
                        'ExtraSpam'  :  "",
                        'logY'       : False,
                        'logX'       : False,
                        'grid'       : True,
                        'savename'   : '[PDIR]/[DATASET]/Observables/stubBx',
                        'executer'   : 'plotter',
                        'type'       : '1D',
    },
    'stubDetId' : {'variable'   : 'stubDetId',
                'bins'       : 1000,
                'extra cuts' : 'True',
                'xlabel'     : 'stubDetId',
                'ylabel'     : 'Yields',
                'xrange'     : [0,10000],
                'ExtraSpam'  :  "",
                'logY'       : False,
                'logX'       : False,
                'grid'       : True,
                'savename'   : '[PDIR]/[DATASET]/Observables/stubDetId',
                'executer'   : 'plotter',
                'type'       : '1D',
    },
    'stubType' : {'variable'   : 'stubType',
                        'bins'       : 10,
                        'extra cuts' : 'True',
                        'xlabel'     : 'stubType',
                        'ylabel'     : 'Yields',
                        'xrange'     : [0.5,10.5],
                        'ExtraSpam'  :  "",
                        'logY'       : False,
                        'logX'       : False,
                        'grid'       : True,
                        'savename'   : '[PDIR]/[DATASET]/Observables/stubType',
                        'executer'   : 'plotter',
                        'type'       : '1D',
    },
    'stubTiming' : {'variable'   : 'stubTiming',
                        'bins'       : 21,
                        'extra cuts' : 'True',
                        'xlabel'     : 'stubTiming',
                        'ylabel'     : 'Yields',
                        'xrange'     : [-10,10],
                        'ExtraSpam'  :  "",
                        'logY'       : False,
                        'logX'       : False,
                        'grid'       : True,
                        'savename'   : '[PDIR]/[DATASET]/Observables/stubTiming',
                        'executer'   : 'plotter',
                        'type'       : '1D',
    },
    'stubLayer': {'variable'   : 'stubLayer',
                        'bins'       : 19,
                        'extra cuts' : 'True',
                        'xlabel'     : 'stubLayer',
                        'ylabel'     : 'Yields',
                        'xrange'     : [-0.5,18.5],
                        'ExtraSpam'  :  "",
                        'logY'       : False,
                        'logX'       : False,
                        'grid'       : True,
                        'savename'   : '[PDIR]/[DATASET]/Observables/stubLayer',
                        'executer'   : 'plotter',
                        'type'       : '1D',
    },
    'inputStubNo' : {'variable'   : 'inputStubNo',
                        'bins'       : 10,
                        'extra cuts' : 'True',
                        'xlabel'     : 'inputStubNo',
                        'ylabel'     : 'Yields',
                        'xrange'     : [0.5,10.5],
                        'ExtraSpam'  :  "",
                        'logY'       : False,
                        'logX'       : False,
                        'grid'       : True,
                        'savename'   : '[PDIR]/[DATASET]/Observables/inputStubNo',
                        'executer'   : 'plotter',
                        'type'       : '1D',
    },
    'inputStubPhi' : {'variable'   : 'inputStubPhi',
                        'bins'       : 1000,
                        'extra cuts' : 'True',
                        'xlabel'     : 'inputStubPhi',
                        'ylabel'     : 'Yields',
                        'xrange'     : [-1000,1000],
                        'ExtraSpam'  :  "",
                        'logY'       : False,
                        'logX'       : False,
                        'grid'       : True,
                        'savename'   : '[PDIR]/[DATASET]/Observables/inputStubPhi',
                        'executer'   : 'plotter',
                        'type'       : '1D',
    },
    'inputStubEta' : {'variable'   : 'inputStubEta',
                        'bins'       : 70,
                        'extra cuts' : 'True',
                        'xlabel'     : 'inputStubEta',
                        'ylabel'     : 'Yields',
                        'xrange'     : [70,140],
                        'ExtraSpam'  :  "",
                        'logY'       : False,
                        'logX'       : False,
                        'grid'       : True,
                        'savename'   : '[PDIR]/[DATASET]/Observables/inputStubEta',
                        'executer'   : 'plotter',
                        'type'       : '1D',
    },
    'inputStubQuality' : {'variable'   : 'inputStubQuality',
                        'bins'       : 12,
                        'extra cuts' : 'True',
                        'xlabel'     : 'inputStubQuality',
                        'ylabel'     : 'Yields',
                        'xrange'     : [0.5,12.5],
                        'ExtraSpam'  :  "",
                        'logY'       : False,
                        'logX'       : False,
                        'grid'       : True,
                        'savename'   : '[PDIR]/[DATASET]/Observables/inputStubQuality',
                        'executer'   : 'plotter',
                        'type'       : '1D',
    },
    'inputStubBx' : {'variable'   : 'inputStubBx',
                        'bins'       : 5,
                        'extra cuts' : 'True',
                        'xlabel'     : 'inputStubBx',
                        'ylabel'     : 'Yields',
                        'xrange'     : [-2,2],
                        'ExtraSpam'  :  "",
                        'logY'       : False,
                        'logX'       : False,
                        'grid'       : True,
                        'savename'   : '[PDIR]/[DATASET]/Observables/inputStubBx',
                        'executer'   : 'plotter',
                        'type'       : '1D',
    },
    'inputStubTiming' : {'variable'   : 'inputStubTiming',
                        'bins'       : 21,
                        'extra cuts' : 'True',
                        'xlabel'     : 'inputStubTiming',
                        'ylabel'     : 'Yields',
                        'xrange'     : [-10,10],
                        'ExtraSpam'  :  "",
                        'logY'       : False,
                        'logX'       : False,
                        'grid'       : True,
                        'savename'   : '[PDIR]/[DATASET]/Observables/inputStubTiming',
                        'executer'   : 'plotter',
                        'type'       : '1D',
    },
    'inputStubLogicLayer' : {'variable'   : 'inputStubLogicLayer',
                        'bins'       : 19,
                        'extra cuts' : 'True',
                        'xlabel'     : 'inputStubLogicLayer',
                        'ylabel'     : 'Yields',
                        'xrange'     : [-0.5,18.5],
                        'ExtraSpam'  :  "",
                        'logY'       : False,
                        'logX'       : False,
                        'grid'       : True,
                        'savename'   : '[PDIR]/[DATASET]/Observables/inputStubLogicLayer',
                        'executer'   : 'plotter',
                        'type'       : '1D',
    },
    'inputStubProc' : {'variable'   : 'inputStubProc',
                        'bins'       : 10,
                        'extra cuts' : 'True',
                        'xlabel'     : 'inputStubProc',
                        'ylabel'     : 'Yields',
                        'xrange'     : [0.5,10.5],
                        'ExtraSpam'  :  "",
                        'logY'       : False,
                        'logX'       : False,
                        'grid'       : True,
                        'savename'   : '[PDIR]/[DATASET]/Observables/inputStubProc',
                        'executer'   : 'plotter',
                        'type'       : '1D',
    },
    'inputStubType' : {'variable'   : 'inputStubType',
                        'bins'       : 10,
                        'extra cuts' : 'True',
                        'xlabel'     : 'inputStubType',
                        'ylabel'     : 'Yields',
                        'xrange'     : [0.5,10.5],
                        'ExtraSpam'  :  "",
                        'logY'       : False,
                        'logX'       : False,
                        'grid'       : True,
                        'savename'   : '[PDIR]/[DATASET]/Observables/inputStubType',
                        'executer'   : 'plotter',
                        'type'       : '1D',
    },
    'inputStubIsMatched' : {'variable'   : 'inputStubIsMatched',
                        'bins'       : 2,
                        'extra cuts' : 'True',
                        'xlabel'     : 'inputStubIsMatched',
                        'ylabel'     : 'Yields',
                        'xrange'     : [-0.5,1.5],
                        'ExtraSpam'  :  "",
                        'logY'       : False,
                        'logX'       : False,
                        'grid'       : True,
                        'savename'   : '[PDIR]/[DATASET]/Observables/inputStubIsMatched',
                        'executer'   : 'plotter',
                        'type'       : '1D',
    },
    'inputStubDeltaPhi0' : {'variable'   : 'inputStubDeltaPhi0',
                        'bins'       : 100,
                        'extra cuts' : 'True',
                        'xlabel'     : 'inputStubDeltaPhi0',
                        'ylabel'     : 'Yields',
                        'xrange'     : [-100,100],
                        'ExtraSpam'  :  "",
                        'logY'       : False,
                        'logX'       : False,
                        'grid'       : True,
                        'savename'   : '[PDIR]/[DATASET]/Observables/inputStubDeltaPhi0',
                        'executer'   : 'plotter',
                        'type'       : '1D',
    },
    'inputStubDeltaPhi1' : {'variable'   : 'inputStubDeltaPhi1',
                        'bins'       : 100,
                        'extra cuts' : 'True',
                        'xlabel'     : 'inputStubDeltaPhi1',
                        'ylabel'     : 'Yields',
                        'xrange'     : [-100,100],
                        'ExtraSpam'  :  "",
                        'logY'       : False,
                        'logX'       : False,
                        'grid'       : True,
                        'savename'   : '[PDIR]/[DATASET]/Observables/inputStubDeltaPhi1',
                        'executer'   : 'plotter',
                        'type'       : '1D',
    },
    'inputStubDeltaPhi2' : {'variable'   : 'inputStubDeltaPhi2',
                        'bins'       : 100,
                        'extra cuts' : 'True',
                        'xlabel'     : 'inputStubDeltaPhi2',
                        'ylabel'     : 'Yields',
                        'xrange'     : [-100,100],
                        'ExtraSpam'  :  "",
                        'logY'       : False,
                        'logX'       : False,
                        'grid'       : True,
                        'savename'   : '[PDIR]/[DATASET]/Observables/inputStubDeltaPhi2',
                        'executer'   : 'plotter',
                        'type'       : '1D',
    },
    'inputStubDeltaPhi3' : {'variable'   : 'inputStubDeltaPhi3',
                        'bins'       : 100,
                        'extra cuts' : 'True',
                        'xlabel'     : 'inputStubDeltaPhi3',
                        'ylabel'     : 'Yields',
                        'xrange'     : [-100,100],
                        'ExtraSpam'  :  "",
                        'logY'       : False,
                        'logX'       : False,
                        'grid'       : True,
                        'savename'   : '[PDIR]/[DATASET]/Observables/inputStubDeltaPhi3',
                        'executer'   : 'plotter',
                        'type'       : '1D',
    },
    'inputStubDeltaPhi4' : {'variable'   : 'inputStubDeltaPhi4',
                        'bins'       : 100,
                        'extra cuts' : 'True',
                        'xlabel'     : 'inputStubDeltaPhi4',
                        'ylabel'     : 'Yields',
                        'xrange'     : [-100,100],
                        'ExtraSpam'  :  "",
                        'logY'       : False,
                        'logX'       : False,
                        'grid'       : True,
                        'savename'   : '[PDIR]/[DATASET]/Observables/inputStubDeltaPhi4',
                        'executer'   : 'plotter',
                        'type'       : '1D',
    },
    'inputStubDeltaPhi5' : {'variable'   : 'inputStubDeltaPhi5',
                        'bins'       : 100,
                        'extra cuts' : 'True',
                        'xlabel'     : 'inputStubDeltaPhi5',
                        'ylabel'     : 'Yields',
                        'xrange'     : [-100,100],
                        'ExtraSpam'  :  "",
                        'logY'       : False,
                        'logX'       : False,
                        'grid'       : True,
                        'savename'   : '[PDIR]/[DATASET]/Observables/inputStubDeltaPhi5',
                        'executer'   : 'plotter',
                        'type'       : '1D',
    },
    'inputStubDeltaPhi6' : {'variable'   : 'inputStubDeltaPhi6',
                        'bins'       : 100,
                        'extra cuts' : 'True',
                        'xlabel'     : 'inputStubDeltaPhi6',
                        'ylabel'     : 'Yields',
                        'xrange'     : [-100,100],
                        'ExtraSpam'  :  "",
                        'logY'       : False,
                        'logX'       : False,
                        'grid'       : True,
                        'savename'   : '[PDIR]/[DATASET]/Observables/inputStubDeltaPhi6',
                        'executer'   : 'plotter',
                        'type'       : '1D',
    },
    'inputStubDeltaPhi7' : {'variable'   : 'inputStubDeltaPhi7',
                        'bins'       : 100,
                        'extra cuts' : 'True',
                        'xlabel'     : 'inputStubDeltaPhi7',
                        'ylabel'     : 'Yields',
                        'xrange'     : [-100,100],
                        'ExtraSpam'  :  "",
                        'logY'       : False,
                        'logX'       : False,
                        'grid'       : True,
                        'savename'   : '[PDIR]/[DATASET]/Observables/inputStubDeltaPhi7',
                        'executer'   : 'plotter',
                        'type'       : '1D',
    },
    'inputStubDeltaEta0' : {'variable'   : 'inputStubDeltaEta0',
                        'bins'       : 100,
                        'extra cuts' : 'True',
                        'xlabel'     : 'inputStubDeltaEta0',
                        'ylabel'     : 'Yields',
                        'xrange'     : [-100,100],
                        'ExtraSpam'  :  "",
                        'logY'       : False,
                        'logX'       : False,
                        'grid'       : True,
                        'savename'   : '[PDIR]/[DATASET]/Observables/inputStubDeltaEta0',
                        'executer'   : 'plotter',
                        'type'       : '1D',
    },
    'inputStubDeltaEta1' : {'variable'   : 'inputStubDeltaEta1',
                        'bins'       : 100,
                        'extra cuts' : 'True',
                        'xlabel'     : 'inputStubDeltaEta1',
                        'ylabel'     : 'Yields',
                        'xrange'     : [-100,100],
                        'ExtraSpam'  :  "",
                        'logY'       : False,
                        'logX'       : False,
                        'grid'       : True,
                        'savename'   : '[PDIR]/[DATASET]/Observables/inputStubDeltaEta1',
                        'executer'   : 'plotter',
                        'type'       : '1D',
    },
    'inputStubDeltaEta2' : {'variable'   : 'inputStubDeltaEta2',
                        'bins'       : 100,
                        'extra cuts' : 'True',
                        'xlabel'     : 'inputStubDeltaEta2',
                        'ylabel'     : 'Yields',
                        'xrange'     : [-100,100],
                        'ExtraSpam'  :  "",
                        'logY'       : False,
                        'logX'       : False,
                        'grid'       : True,
                        'savename'   : '[PDIR]/[DATASET]/Observables/inputStubDeltaEta2',
                        'executer'   : 'plotter',
                        'type'       : '1D',
    },
    'inputStubDeltaEta3' : {'variable'   : 'inputStubDeltaEta3',
                        'bins'       : 100,
                        'extra cuts' : 'True',
                        'xlabel'     : 'inputStubDeltaEta3',
                        'ylabel'     : 'Yields',
                        'xrange'     : [-100,100],
                        'ExtraSpam'  :  "",
                        'logY'       : False,
                        'logX'       : False,
                        'grid'       : True,
                        'savename'   : '[PDIR]/[DATASET]/Observables/inputStubDeltaEta3',
                        'executer'   : 'plotter',
                        'type'       : '1D',
    },
    'inputStubDeltaEta4' : {'variable'   : 'inputStubDeltaEta4',
                        'bins'       : 100,
                        'extra cuts' : 'True',
                        'xlabel'     : 'inputStubDeltaEta4',
                        'ylabel'     : 'Yields',
                        'xrange'     : [-100,100],
                        'ExtraSpam'  :  "",
                        'logY'       : False,
                        'logX'       : False,
                        'grid'       : True,
                        'savename'   : '[PDIR]/[DATASET]/Observables/inputStubDeltaEta4',
                        'executer'   : 'plotter',
                        'type'       : '1D',
    },
    'inputStubDeltaEta5' : {'variable'   : 'inputStubDeltaEta5',
                        'bins'       : 100,
                        'extra cuts' : 'True',
                        'xlabel'     : 'inputStubDeltaEta5',
                        'ylabel'     : 'Yields',
                        'xrange'     : [-100,100],
                        'ExtraSpam'  :  "",
                        'logY'       : False,
                        'logX'       : False,
                        'grid'       : True,
                        'savename'   : '[PDIR]/[DATASET]/Observables/inputStubDeltaEta5',
                        'executer'   : 'plotter',
                        'type'       : '1D',
    },
    'inputStubDeltaEta6' : {'variable'   : 'inputStubDeltaEta6',
                        'bins'       : 100,
                        'extra cuts' : 'True',
                        'xlabel'     : 'inputStubDeltaEta6',
                        'ylabel'     : 'Yields',
                        'xrange'     : [-100,100],
                        'ExtraSpam'  :  "",
                        'logY'       : False,
                        'logX'       : False,
                        'grid'       : True,
                        'savename'   : '[PDIR]/[DATASET]/Observables/inputStubDeltaEta6',
                        'executer'   : 'plotter',
                        'type'       : '1D',
    },
    'inputStubDeltaEta7' : {'variable'   : 'inputStubDeltaEta7',
                        'bins'       : 100,
                        'extra cuts' : 'True',
                        'xlabel'     : 'inputStubDeltaEta7',
                        'ylabel'     : 'Yields',
                        'xrange'     : [-100,100],
                        'ExtraSpam'  :  "",
                        'logY'       : False,
                        'logX'       : False,
                        'grid'       : True,
                        'savename'   : '[PDIR]/[DATASET]/Observables/inputStubDeltaEta7',
                        'executer'   : 'plotter',
                        'type'       : '1D',
    },
    
}
'''
